### ISSUE TITLE
没有print提示

### ISSUE THREAD

**Issue by sandy-shi** [maoyonglong/codemirror-demo#1]
我在vue项目中，用了showHint的方法，但是我用的时候没有print提醒，我想问一下，你用的是codemirror的哪个版本

**Comment by maoyonglong** [comment]
在mode/python/python.js中添加print关键字
![image](https://user-images.githubusercontent.com/37609752/85521418-ce120c80-b636-11ea-9f40-9ad08e3db88f.png)

**Comment by maoyonglong** [comment]
> 我在vue项目中，用了showHint的方法，但是我用的时候没有print提醒，我想问一下，你用的是codemirror的哪个版本

在mode/python/python.js中添加print关键字
![image](https://user-images.githubusercontent.com/37609752/85521418-ce120c80-b636-11ea-9f40-9ad08e3db88f.png)
